name: coil
description: A music player that connnects to Piped.
publish_to: 'none'
version: 1.9.12

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http: any
  path: any
  path_provider: any
    #open_as_default: any
  permission_handler: any
  shared_preferences: any
  url_launcher: any
  flutter_file_saver: any

  #audio-packages
  just_audio: any
  #simple_audio: ^1.8.0

  audio_service: any


  flutter:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: any
  flutter_test:
    sdk: flutter

  flutter_lints: any

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  #    flutter pub run flutter_launcher_icons:main
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  fonts: 
    - family: JetBrainsMono
      fonts:
        - asset : assets/fonts/JetBrainsMono-Regular.ttf

  assets:
    - assets/translations/
