name: coil
description: A music player that connnects to Piped.
publish_to: 'none'
version: 1.9.9

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  http: any
  path: any
  path_provider: ^2.1.1
  open_as_default: ^0.0.3
  permission_handler: ^11.1.0
  shared_preferences: ^2.2.2
  url_launcher: ^6.2.1
  flutter_file_saver: any

  #audio-packages
  just_audio: ^0.9.36
  #simple_audio: ^1.8.0

  audio_service: ^0.18.12


  flutter:
    sdk: flutter


dev_dependencies:
  flutter_launcher_icons: ^0.11.0
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  #    flutter pub run flutter_launcher_icons:main
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/icon.png"
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  fonts: 
    - family: JetBrainsMono
      fonts:
        - asset : fonts/JetBrainsMono-Regular.ttf

  assets:
    - assets/translations/
